var nama = prompt("Silahkan ketik nama anda:")
var tanggal_lahir = prompt("Silahkan ketik tanggal lahir Anda:")
var alamat = prompt("Silahkan ketik alamat lengkap Anda:")
var pendidikan = prompt("Silahkan ketik jenjang pendidikan terakhir Anda:")
alert("Data berhasil di simpan \nTerima Kasih atas partisipasi Anda")
console.log("nama: ", nama)
console.log("tanggal lahir: ", tanggal_lahir)
console.log("alamat: ", alamat)
console.log("pendidikan: ", pendidikan)
